PlcCreatorSystem_WEB/Controllers/HmiController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using PlcCreatorSystem_WEB.Models;
using PlcCreatorSystem_Utility;
using PlcCreatorSystem_WEB.Models.Dto;
using PlcCreatorSystem_WEB.Models.VM;
using PlcCreatorSystem_WEB.Services.IServices;
using PlcCreatorSystem_WEB.Services;
using System.Security.Claims;

namespace PlcCreatorSystem_WEB.Controllers
{
    public class HmiController : Controller
    {
        private readonly IHmiService _hmiService;
        private readonly IUserService _userService;
        private readonly IMapper _mapper;
        

        public HmiController(IHmiService hmiService, IUserService userService, IMapper mapper )
        {
            _hmiService = hmiService;
            _userService = userService;
            _mapper = mapper;
        }

        [Authorize(Roles = "admin,engineer,custom")]
        public async Task<IActionResult> IndexHmi()
        {
            List<HmiDTO> list = new();
            var response = await _hmiService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<HmiDTO>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        [Authorize(Roles = "admin,engineer")]
        public async Task<IActionResult> CreateHmi()
        {
            HmiCreateVM hmiCreateVM = new();
            await PopulateLookups(hmiCreateVM);
            return View(hmiCreateVM);
        }

        [Authorize(Roles = "admin,engineer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateHmi(HmiCreateVM model)
        {

            if (ModelState.IsValid)
            {
                var response = await _hmiService.CreateAsync<APIResponse>(model.hmiCreateVM, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Plc created successfully";
                    return RedirectToAction(nameof(IndexHmi));
                }
                else
                {
                    if (response.ErrorsMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorsMessages.FirstOrDefault());
                    }
                }
            }
            await PopulateLookups(model);
            return View(model);
        }

        [Authorize(Roles = "admin,engineer")]
        public async Task<IActionResult> UpdateHmi(int hmiId)
        {
            HmiUpdateVM hmiVM = new();
            var response = await _hmiService.GetAsync<APIResponse>(hmiId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                HmiDTO? model = JsonConvert.DeserializeObject<HmiDTO>(Convert.ToString(response.Result));
                hmiVM.hmiUpdateVM = _mapper.Map<HmiUpdateDTO>(model);
                await PopulateLookups(hmiVM);
                return View(hmiVM);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin,engineer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateHmi(HmiUpdateVM model)
        {

            if (ModelState.IsValid)
            {
                var response = await _hmiService.UpdateAsync<APIResponse>(model.hmiUpdateVM, HttpContext.Session.GetString(SD.SessionToken));
                TempData["success"] = "Hmi updated successfully";
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexHmi));
                }
                else
                {
                    if (response.ErrorsMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorsMessages.FirstOrDefault());
                    }
                }
            }
            await PopulateLookups(model);
            return View(model);
        }

        [Authorize(Roles = "admin,engineer")]
        public async Task<IActionResult> DeleteHmi(int hmiId)
        {
            HmiDeleteVM hmiVM = new();
            var response = await _hmiService.GetAsync<APIResponse>(hmiId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                HmiDTO model = JsonConvert.DeserializeObject<HmiDTO>(Convert.ToString(response.Result));
                hmiVM.hmiDeleteVM = model;

                await PopulateLookups(hmiVM);

                return View(hmiVM);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin,engineer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteHmi(HmiDeleteVM model)
        {
            var response = await _hmiService.DeleteAsync<APIResponse>(model.hmiDeleteVM.Id, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "HMI deleted successfully";
                return RedirectToAction(nameof(IndexHmi));
            }
            else
            {
                if (response.ErrorsMessages.Count > 0)
                {
                    ModelState.AddModelError("ErrorMessages", response.ErrorsMessages.FirstOrDefault());
                }
            }
            await PopulateLookups(model);
            return View(model);
        }

        //************************************************************************************************
        //****************************** Methods - PopulateLookups ***************************************
        //************************************************************************************************
        //HmiCreateVM
        private async Task PopulateLookups(HmiCreateVM model)
        {
            var userIdStr = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (int.TryParse(userIdStr, out var id))
            {
                model.hmiCreateVM.UserID = id;
            }
            var responseUser = await _userService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (responseUser != null && responseUser.IsSuccess == true)
            {
                model.usersList = JsonConvert.DeserializeObject<List<UserDTO>>
                    (Convert.ToString(responseUser.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }

        }

        //HmiUpdateVM
        private async Task PopulateLookups(HmiUpdateVM model)
        {
            var responseUser = await _userService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (responseUser != null && responseUser.IsSuccess == true)
            {
                model.usersList = JsonConvert.DeserializeObject<List<UserDTO>>
                    (Convert.ToString(responseUser.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }

        }

        //HmiDeleteVM
        private async Task PopulateLookups(HmiDeleteVM model)
        {
            var responseHmi = await _userService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (responseHmi != null && responseHmi.IsSuccess == true)
            {
                model.usersList = JsonConvert.DeserializeObject<List<UserDTO>>
                    (Convert.ToString(responseHmi.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }

        }
    }
}

PlcCreatorSystem_WEB/Views/Hmi/CreateHmi.cshtml
@model PlcCreatorSystem_WEB.Models.VM.HmiCreateVM
@using System.Security.Claims
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc
@{
    var user = httpAcc.HttpContext.User;
}

<form asp-action="CreateHmi">
    <br />
    <div class="container border p-3">
        <h1 class="text-primaey">Create Hmi</h1>
        <hr />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-dnager"></div>

            <div class="col-2">
                <label asp-for="hmiCreateVM.Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="hmiCreateVM.Name" class="form-control" />
                <span asp-validation-for="hmiCreateVM.Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="hmiCreateVM.IP" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="hmiCreateVM.IP" class="form-control" />
                <span asp-validation-for="hmiCreateVM.IP" class="text-danger"></span>
            </div>
             
            <div class="col-2">
                <label asp-for="hmiCreateVM.Identyfier" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="hmiCreateVM.Identyfier" class="form-control" />
                <span asp-validation-for="hmiCreateVM.Identyfier" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="hmiCreateVM.Details" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10  pb-3">
                <textarea asp-for="hmiCreateVM.Details" class="form-control" rows="5"></textarea>
                <span asp-validation-for="hmiCreateVM.Details" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Author</label>
            </div>
            <div class="col-10 pb-3">
                <div class="btn btn-warning form-control text-center" style="pointer-events:none; cursor:default;">
                    @User.Identity?.Name
                </div>

                <input type="hidden" asp-for="hmiCreateVM.UserID"
                       value="@User.FindFirstValue(ClaimTypes.NameIdentifier)" />
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexHmi" asp-controller="HMI" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success from-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

PlcCreatorSystem_WEB/Views/Hmi/DeleteHmi.cshtml
@model PlcCreatorSystem_WEB.Models.VM.HmiDeleteVM

<form asp-action="DeleteHmi">
    <br />
    <div class="container border p-3">
        <h1 class="text-primaey">DeleteHmi</h1>
        <hr />

        <input hidden asp-for="hmiDeleteVM.Id" />
        <div class="row">
            <div class="col-2">
                <label asp-for="hmiDeleteVM.Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="hmiDeleteVM.Name" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="hmiDeleteVM.IP" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="hmiDeleteVM.IP" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="hmiDeleteVM.Identyfier" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10  pb-3">
                <input asp-for="hmiDeleteVM.Identyfier" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="hmiDeleteVM.Details" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10  pb-3">
                <textarea asp-for="hmiDeleteVM.Details" disabled class="form-control" rows="5"></textarea>
            </div>

            <div class="col-2">
                <label asp-for="hmiDeleteVM.UserID" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="hmiDeleteVM.UserID" disabled class="form-control" rows="1"></textarea>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexHmi" asp-controller="HMI" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger from-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

PlcCreatorSystem_WEB/Views/Hmi/IndexHmi.cshtml
@using PlcCreatorSystem_Utility;
@model IEnumerable<PlcCreatorSystem_WEB.Models.Dto.HmiDTO>
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc
@{
    var user = httpAcc.HttpContext.User;
    var role = user?.Claims.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Role)?.Value;
    var token = httpAcc.HttpContext?.Session.GetString(SD.SessionToken);
}

<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">HMI List</h1>
        </div>
        @if ((string.Equals(role, "admin", StringComparison.OrdinalIgnoreCase)) || (string.Equals(role, "engineer", StringComparison.OrdinalIgnoreCase)))
        {
            <div class="col text-end pt-1">
                <a asp-controller="Hmi" asp-action="CreateHmi" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i>Create New HMI</a>
            </div>
        }
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    IP
                </th>
                <th>
                    Identyfier
                </th>
                <th>
                    Details
                </th>
                <th>
                    Author
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.IP</td>
                    <td>@item.Identyfier</td>
                    <td>@item.Details</td>
                    <td>@item.LocalUser?.Name</td>
                    @if ((string.Equals(role, "admin", StringComparison.OrdinalIgnoreCase)) || (string.Equals(role, "engineer", StringComparison.OrdinalIgnoreCase)))
                    {
                        <td>
                            <a asp-controller="HMI" asp-action="UpdateHmi" asp-route-hmiId="@item.Id" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
                            <a asp-controller="HMI" asp-action="DeleteHmi" asp-route-hmiId="@item.Id" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>

                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

PlcCreatorSystem_WEB/Views/Hmi/UpdateHmi.cshtml
@model PlcCreatorSystem_WEB.Models.VM.HmiUpdateVM

<form asp-action="UpdateHmi">
    <br />
    <div class="container border p-3">
        <h1 class="text-primaey">Update Hmi</h1>
        <hr />

        <input hidden asp-for="hmiUpdateVM.Id" />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="hmiUpdateVM.Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="hmiUpdateVM.Name" class="form-control" />
                <span asp-validation-for="hmiUpdateVM.Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="hmiUpdateVM.IP" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="hmiUpdateVM.IP" class="form-control" />
                <span asp-validation-for="hmiUpdateVM.IP" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="hmiUpdateVM.Identyfier" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="hmiUpdateVM.Identyfier" class="form-control" />
                <span asp-validation-for="hmiUpdateVM.Identyfier" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="hmiUpdateVM.Details" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10  pb-3">
                <textarea asp-for="hmiUpdateVM.Details" class="form-control" rows="5"></textarea>
                <span asp-validation-for="hmiUpdateVM.Details" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="hmiUpdateVM.UserID" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="hmiUpdateVM.UserID" class="form-select" asp-items="@Model.usersList">
                    <option disabled selected>--Select User--</option>
                </select>
                <span asp-validation-for="hmiUpdateVM.UserID" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexHmi" asp-controller="Hmi" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-success from-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}