PlcCreatorSystem_WEB/Controllers/PlcController.cs
using AutoMapper;
using Azure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using PlcCreatorSystem_Utility;
using PlcCreatorSystem_WEB.Models;
using PlcCreatorSystem_WEB.Models.Dto;
using PlcCreatorSystem_WEB.Models.VM;
using PlcCreatorSystem_WEB.Services.IServices;
using System.Security.Claims;

namespace PlcCreatorSystem_WEB.Controllers
{
    public class PlcController : Controller
    {
        private readonly IPlcService _plcService;
        private readonly IMapper _mapper;
        private readonly IUserService _userService;

        public PlcController(IPlcService plcService, IUserService userService, IMapper mapper)
        {
            _plcService = plcService;
            _userService = userService;
            _mapper = mapper;
        }

        [Authorize(Roles = "admin,engineer,custom")]
        public async Task<IActionResult> IndexPlc()
        {
            List<PlcDTO> list = new();
            var response = await _plcService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<PlcDTO>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        [Authorize(Roles = "admin,engineer")]
        public async Task<IActionResult> CreatePlc()
        {
            PlcCreateVM plcCreateVM = new();
            await PopulateLookups(plcCreateVM);
            return View(plcCreateVM);
        }

        [Authorize(Roles = "admin,engineer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePlc(PlcCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _plcService.CreateAsync<APIResponse>(model.plcCreateVM, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Plc created successfully";
                    return RedirectToAction(nameof(IndexPlc));
                }
                else
                {
                    if (response.ErrorsMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorsMessages.FirstOrDefault());
                    }
                }
            }else
            {
                //ModelState.AddModelError("ErrorMessages", model.ErrorsMessages.FirstOrDefault());//Error model is not Valid
            }
            await PopulateLookups(model);
            return View(model);
        }

        [Authorize(Roles = "admin,engineer")]
        public async Task<IActionResult> UpdatePlc(int plcId)
        {
            PlcUpdateVM plcVM = new();
            var response = await _plcService.GetAsync<APIResponse>(plcId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                PlcDTO model = JsonConvert.DeserializeObject<PlcDTO>(Convert.ToString(response.Result));
                plcVM.plcUpdateVM = _mapper.Map<PlcUpdateDTO>(model);
                await PopulateLookups(plcVM);
                return View(plcVM);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin,engineer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdatePlc(PlcUpdateVM model)
        {

            if (ModelState.IsValid)
            {
                TempData["success"] = "Plc updated successfully";
                var response = await _plcService.UpdateAsync<APIResponse>(model.plcUpdateVM, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexPlc));
                }
                else
                {
                    if (response.ErrorsMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorsMessages.FirstOrDefault());
                    }
                }
            }
            await PopulateLookups(model);
            return View(model);
        }

        [Authorize(Roles = "admin,engineer")]
        public async Task<IActionResult> DeletePlc(int plcId)
        {
            PlcDeleteVM plcVM = new();
            var response = await _plcService.GetAsync<APIResponse>(plcId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                PlcDTO model = JsonConvert.DeserializeObject<PlcDTO>(Convert.ToString(response.Result));
                plcVM.plcDeleteVM = model;

                await PopulateLookups(plcVM);

                return View(plcVM);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin,engineer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePlc(PlcDeleteVM model)
        {
            var response = await _plcService.DeleteAsync<APIResponse>(model.plcDeleteVM.Id, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "PLC deleted successfully";
                return RedirectToAction(nameof(IndexPlc));
            }
            else
            {
                if (response.ErrorsMessages.Count > 0)
                {
                    ModelState.AddModelError("ErrorMessages", response.ErrorsMessages.FirstOrDefault());
                }
            }
            await PopulateLookups(model);
            return View(model);
        }
        //************************************************************************************************
        //****************************** Methods - PopulateLookups ***************************************
        //************************************************************************************************
        //HmiCreateVM
        private async Task PopulateLookups(PlcCreateVM model)
        {
            var userIdStr = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (int.TryParse(userIdStr, out var id))
            {
                model.plcCreateVM.UserID = id;
            }
            var responseHmi = await _userService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (responseHmi != null && responseHmi.IsSuccess == true)
            {
                model.usersList = JsonConvert.DeserializeObject<List<UserDTO>>
                    (Convert.ToString(responseHmi.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }

        }

        //HmiUpdateVM
        private async Task PopulateLookups(PlcUpdateVM model)
        {
            var responseHmi = await _userService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (responseHmi != null && responseHmi.IsSuccess == true)
            {
                model.usersList = JsonConvert.DeserializeObject<List<UserDTO>>
                    (Convert.ToString(responseHmi.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }

        }

        //HmiDeleteVM
        private async Task PopulateLookups(PlcDeleteVM model)
        {
            var responseHmi = await _userService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (responseHmi != null && responseHmi.IsSuccess == true)
            {
                model.usersList = JsonConvert.DeserializeObject<List<UserDTO>>
                    (Convert.ToString(responseHmi.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }

        }
    }
}

PlcCreatorSystem_WEB/Views/Plc/CreatePlc.cshtml
@model PlcCreatorSystem_WEB.Models.VM.PlcCreateVM
@using System.Security.Claims
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc
@{
    var user = httpAcc.HttpContext.User;
}

<form asp-action="CreatePlc">
    <br />
    <div class="container border p-3">
        <h1 class="text-primaey">Create Plc</h1>
        <hr />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-dnager"></div>

            <div class="col-2">
                <label asp-for="plcCreateVM.Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcCreateVM.Name" class="form-control" />
                <span asp-validation-for="plcCreateVM.Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcCreateVM.Subnet_X1" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcCreateVM.Subnet_X1" class="form-control" />
                <span asp-validation-for="plcCreateVM.Subnet_X1" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcCreateVM.IP_X1" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcCreateVM.IP_X1" class="form-control" />
                <span asp-validation-for="plcCreateVM.IP_X1" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcCreateVM.Subnet_X2" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcCreateVM.Subnet_X2" class="form-control" />
                <span asp-validation-for="plcCreateVM.Subnet_X2" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcCreateVM.IP_X2" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcCreateVM.IP_X2" class="form-control" />
                <span asp-validation-for="plcCreateVM.IP_X2" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcCreateVM.Identyfier" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcCreateVM.Identyfier" class="form-control" />
                <span asp-validation-for="plcCreateVM.Identyfier" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcCreateVM.Details" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10  pb-3">
                <textarea asp-for="plcCreateVM.Details" class="form-control" rows="5"></textarea>
                <span asp-validation-for="plcCreateVM.Details" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Author</label>
            </div>
            <div class="col-10 pb-3">
                <div class="btn btn-warning form-control text-center" style="pointer-events:none; cursor:default;">
                    @User.Identity?.Name
                </div>

                <input type="hidden" asp-for="plcCreateVM.UserID"
                           value="@User.FindFirstValue(ClaimTypes.NameIdentifier)" />
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexPlc" asp-controller="PLC" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success from-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

PlcCreatorSystem_WEB/Views/Plc/DeletePlc.cshtml
@model PlcCreatorSystem_WEB.Models.VM.PlcDeleteVM

<form asp-action="DeletePlc">
    <br />
    <div class="container border p-3">
        <h1 class="text-primaey">DeletePlc</h1>
        <hr />

        <input hidden asp-for="plcDeleteVM.Id" />
        <div class="row">
            <div class="col-2">
                <label asp-for="plcDeleteVM.Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcDeleteVM.Name" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="plcDeleteVM.Subnet_X1" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcDeleteVM.Subnet_X1" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="plcDeleteVM.IP_X1" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcDeleteVM.IP_X1" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="plcDeleteVM.Subnet_X2" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcDeleteVM.Subnet_X2" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="plcDeleteVM.IP_X2" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcDeleteVM.IP_X2" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="plcDeleteVM.Identyfier" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10  pb-3">
                <input asp-for="plcDeleteVM.Identyfier" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="plcDeleteVM.Details" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10  pb-3">
                <textarea asp-for="plcDeleteVM.Details" disabled class="form-control" rows="5"></textarea>
            </div>

            <div class="col-2">
                <label asp-for="plcDeleteVM.UserID" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="plcDeleteVM.UserID" disabled class="form-control" rows="1"></textarea>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexPlc" asp-controller="PLC" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger from-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

PlcCreatorSystem_WEB/Views/Plc/IndexPlc.cshtml
@using PlcCreatorSystem_Utility;
@model IEnumerable<PlcCreatorSystem_WEB.Models.Dto.PlcDTO>
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc
@{
    var user = httpAcc.HttpContext.User;
    var role = user?.Claims.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Role)?.Value;
    var token = httpAcc.HttpContext?.Session.GetString(SD.SessionToken);
}

<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">PLC List</h1>
        </div>
        @if ((string.Equals(role, "admin", StringComparison.OrdinalIgnoreCase)) || (string.Equals(role, "engineer", StringComparison.OrdinalIgnoreCase)))
        {
            <div class="col text-end pt-1">
                <a asp-controller="Plc" asp-action="CreatePlc" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i>Create New PLC</a>
            </div>
        }
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Subnet_X1
                </th>
                <th>
                    IP_X1
                </th>
                <th>
                    Subnet_X2
                </th>
                <th>
                    IP_X2
                </th>
                <th>
                    Identyfier
                </th>
                <th>
                    Details
                </th>
                <th>
                    Author
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Subnet_X1</td>
                    <td>@item.IP_X1</td>
                    <td>@item.Subnet_X2</td>
                    <td>@item.IP_X2</td>
                    <td>@item.Identyfier</td>
                    <td>@item.Details</td>
                    <td>@item.LocalUser?.Name</td>
                    @if ((string.Equals(role, "admin", StringComparison.OrdinalIgnoreCase)) || (string.Equals(role, "engineer", StringComparison.OrdinalIgnoreCase)))
                    {
                        <td>
                            <a asp-controller="PLC" asp-action="UpdatePlc" asp-route-plcId="@item.Id" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
                            <a asp-controller="PLC" asp-action="DeletePlc" asp-route-plcId="@item.Id" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>

                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

PlcCreatorSystem_WEB/Views/Plc/UpdatePlc.cshtml
@model PlcCreatorSystem_WEB.Models.VM.PlcUpdateVM

<form asp-action="UpdatePlc">
    <br />
    <div class="container border p-3">
        <h1 class="text-primaey">Update Plc</h1>
        <hr />

        <input hidden asp-for="plcUpdateVM.Id" />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-dnager"></div>

            <div class="col-2">
                <label asp-for="plcUpdateVM.Name" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcUpdateVM.Name" class="form-control" />
                <span asp-validation-for="plcUpdateVM.Name" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcUpdateVM.Subnet_X1" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcUpdateVM.Subnet_X1" class="form-control" />
                <span asp-validation-for="plcUpdateVM.Subnet_X1" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcUpdateVM.IP_X1" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcUpdateVM.IP_X1" class="form-control" />
                <span asp-validation-for="plcUpdateVM.IP_X1" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcUpdateVM.Subnet_X2" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcUpdateVM.Subnet_X2" class="form-control" />
                <span asp-validation-for="plcUpdateVM.Subnet_X2" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcUpdateVM.IP_X2" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcUpdateVM.IP_X2" class="form-control" />
                <span asp-validation-for="plcUpdateVM.IP_X2" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcUpdateVM.Identyfier" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="plcUpdateVM.Identyfier" class="form-control" />
                <span asp-validation-for="plcUpdateVM.Identyfier" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcUpdateVM.Details" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10  pb-3">
                <textarea asp-for="plcUpdateVM.Details" class="form-control" rows="5"></textarea>
                <span asp-validation-for="plcUpdateVM.Details" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="plcUpdateVM.UserID" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="plcUpdateVM.UserID" class="form-select" asp-items="@Model.usersList">
                    <option disabled selected>--Select User--</option>
                </select>
                <span asp-validation-for="plcUpdateVM.UserID" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexPlc" asp-controller="PLC" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-success from-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}